apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-devops-app
  template:
    metadata:
      labels:
        app: gcp-devops-app
    spec:
      containers:
        - name: app
          image: gcp-devops-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
