apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-devops-app
  template:
    metadata:
      labels:
        app: gcp-devops-app
    spec:
      containers:
        - name: app
          image: asia-south1-docker.pkg.dev/theena-devops/theena-devops-repo/gcp-devops-app
          ports:
            - containerPort: 8080
